config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users,
    controllers: {
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations',
      sessions: 'sessions'
    },
    path_names: {
      sign_in:  'login',
      sign_out: 'logout',
      sign_up:  'register'
    }
    
  root 'public#home'
  get "sitemap.xml" => "sitemaps#index", format: "xml", as: 'sitemap'
  
  resources :videos do
    collection do
      get :episode
      get :results
    end
  end
  resources :wishlists

  namespace :userpage do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :members
    resources :videos
    resources :activities
    resources :wishlists
  end

  namespace :backend do
    get "dashboard", to: 'home#dashboard', as: 'dashboard_admin'
    resources :admins
    resources :members do
      collection do
        get :multiple_action
      end
    end
    resources :category_videos
    resources :videos do
      collection do
        get :multiple_action
      end
    end
    resources :web_settings
  end
end

app/views/shareds/_analytic.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-85330735-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/shareds/_fb_sdk.html.erb
<div id="fb-root"></div>
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '1778255869109142',
      xfbml      : true,
      version    : 'v2.8'
    });
  };

  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>

app/views/shareds/_featured.html.haml
%h4.titleize FEATURED       
%ul.latest-list-full
  - @featured_videos.each_with_index do |v, index|
    %li
      = link_to video_path(v) do
        .cover
          - cache ["cover_video__featured_#{v.id}_#{v.updated_at.to_time.to_i}"] do
            = image_tag v.cover_image.url(:small)
        .category #{v.type_video.titleize if v.type_video.present?}
        .title #{v.title}
        %small.view-eye
          %i.fa.fa-eye
          #{v.impressionist_count} Views

app/views/shareds/_footer.html.haml
- cache("footer", expires_in: 10.day) do
  %footer
    .container.new-container{style: 'padding:10px;'}
      %center
        Copyright © 2016 - 2017 sovies-series.com | Portal Video In The World

app/views/shareds/_meta_global.html.haml
%meta{'http-equiv'=>"X-UA-Compatible", 'content'=>"IE=edge,IE=9,IE=8,chrome=1"}
%meta{charset: "utf-8"}
%meta{name: "viewport", content: "width=device-width, initial-scale=1.0, user-scalable=0, minimum-scale=1.0, maximum-scale=1.0"}
%meta{name: "apple-mobile-web-app-capable", content: "yes"}
%meta{name: "apple-mobile-web-app-status-bar-style", content: "black"}
%meta{:content => "542f9b74e6", :name => "verify-admitad"}
= favicon_link_tag "#{web_setting.favicon.url}"

- if params[:controller] == 'videos' && params[:action] == 'show'
  - @title = @video.title
  - @url = video_url(@video)
  %title
    = @title
  %meta{name: "keywords", content: "#{@title}"}
  %meta{name: "description", content: "#{@video.description}"}
  %meta{name: "author", content: "sovies-series.com"}
  %meta{'property'=>"og:title", 'content'=>"#{@title}"}
  %meta{'property'=>"og:type", 'content'=>"website"}
  %meta{'property'=>"og:site_name", 'content'=>"#{@url}"}
  %meta{'property'=>"og:url", 'content'=>"#{@url}"}
  %meta{'property'=>"og:image", 'content'=>"#{image_url @video.cover_image.url(:medium)}"}
  %meta{'property'=>"og:description", 'content'=>"#{strip_tags(@video.description) if @video.description.present?}"}
  %meta{'property'=>"article:publisher", 'content'=>"movies-series"}
  %meta{'name'=>"twitter:card", 'content'=>"summary"}
  %meta{'name'=>"twitter:url", 'content'=>"#{@url}"}
  %meta{'name'=>"twitter:title", 'content'=>"#{@title}"}
  %meta{'name'=>"twitter:description", 'content'=>"#{strip_tags(@video.description) if @video.description.present?}"}
  %meta{'name'=>"twitter:creator", 'content'=>"sovies-series.com"}
  %meta{'name'=>"twitter:image:src", 'content'=>"#{image_url @video.cover_image.url(:medium)}"}
- elsif params[:controller] == 'videos' && params[:action] == 'episode'
  - @title = @episode.title
  - @url = episode_videos_url(episode: @episode)
  %title
    = @title
  %meta{name: "keywords", content: "#{@title}"}
  %meta{name: "description", content: "#{@video.description}"}
  %meta{name: "author", content: "sovies-series.com"}
  %meta{'property'=>"og:title", 'content'=>"#{@title}"}
  %meta{'property'=>"og:type", 'content'=>"website"}
  %meta{'property'=>"og:site_name", 'content'=>"#{@url}"}
  %meta{'property'=>"og:url", 'content'=>"#{@url}"}
  - if @episode.cover_image.blank?
    %meta{'property'=>"og:image", 'content'=>"#{image_url @video.cover_image.url(:medium)}"}
  - else
    %meta{'property'=>"og:image", 'content'=>"#{image_url @episode.cover_image.url(:medium)}"}  
  %meta{'property'=>"og:description", 'content'=>"#{strip_tags(@video.description) if @video.description.present?}"}
  %meta{'property'=>"article:publisher", 'content'=>"movies-series"}
  %meta{'name'=>"twitter:card", 'content'=>"summary"}
  %meta{'name'=>"twitter:url", 'content'=>"#{@url}"}
  %meta{'name'=>"twitter:title", 'content'=>"#{@title}"}
  %meta{'name'=>"twitter:description", 'content'=>"#{strip_tags(@video.description) if @video.description.present?}"}
  %meta{'name'=>"twitter:creator", 'content'=>"sovies-series.com"}
  - if @episode.cover_image.blank?
    %meta{'name'=>"twitter:image:src", 'content'=>"#{image_url @video.cover_image.url(:medium)}"}
  - else
    %meta{'name'=>"twitter:image:src", 'content'=>"#{image_url @episode.cover_image.url(:medium)}"}
- elsif params[:controller] == 'videos' && params[:action] == 'index'
  - @title = @category_video.name
  - @url = videos_url(category: @category_video)
  %title
    = @title
  %meta{name: "keywords", content: "#{@title}"}
  %meta{name: "description", content: "#{@category_video.description}"}
  %meta{name: "author", content: "sovies-series.com"}
  %meta{'property'=>"og:title", 'content'=>"#{@title}"}
  %meta{'property'=>"og:type", 'content'=>"website"}
  %meta{'property'=>"og:site_name", 'content'=>"#{@url}"}
  %meta{'property'=>"og:url", 'content'=>"#{@url}"}
  %meta{'property'=>"og:image", 'content'=>"#{image_url @category_video.cover_image.url(:medium)}"}
  %meta{'property'=>"og:description", 'content'=>"#{strip_tags(@category_video.description) if @category_video.description.present?}"}
  %meta{'property'=>"article:publisher", 'content'=>"movies-series"}
  %meta{'name'=>"twitter:card", 'content'=>"summary"}
  %meta{'name'=>"twitter:url", 'content'=>"#{@url}"}
  %meta{'name'=>"twitter:title", 'content'=>"#{@title}"}
  %meta{'name'=>"twitter:description", 'content'=>"#{strip_tags(@category_video.description) if @category_video.description.present?}"}
  %meta{'name'=>"twitter:creator", 'content'=>"sovies-series.com"}
  %meta{'name'=>"twitter:image:src", 'content'=>"#{image_url @category_video.cover_image.url(:medium)}"}
- else
  - @title = web_setting.title
  - @url = root_url
  %title
    = @title
  %meta{name: "keywords", content: "#{web_setting.keywords}"}
  %meta{name: "description", content: "#{web_setting.description}"}
  %meta{name: "author", content: "sovies-series.com"}
  %meta{'property'=>"og:title", 'content'=>"#{@title}"}
  %meta{'property'=>"og:type", 'content'=>"website"}
  %meta{'property'=>"og:site_name", 'content'=>"#{@url}"}
  %meta{'property'=>"og:url", 'content'=>"#{@url}"}
  %meta{'property'=>"og:image", 'content'=>"#{image_url web_setting.logo.url}"}
  %meta{'property'=>"og:description", 'content'=>"#{strip_tags(web_setting.description) if web_setting.description.present?}"}
  %meta{'property'=>"article:publisher", 'content'=>"movies-series"}
  %meta{'name'=>"twitter:card", 'content'=>"summary"}
  %meta{'name'=>"twitter:url", 'content'=>"#{@url}"}
  %meta{'name'=>"twitter:title", 'content'=>"#{@title}"}
  %meta{'name'=>"twitter:description", 'content'=>"#{strip_tags(web_setting.description) if web_setting.description.present?}"}
  %meta{'name'=>"twitter:creator", 'content'=>"sovies-series.com"}
  %meta{'name'=>"twitter:image:src", 'content'=>"#{image_url web_setting.logo.url}"}

%meta{ 'content'=>'true', 'name'=>'MSSmartTagsPreventParsing'}
%meta{ 'content'=>'text/html; charset=UTF-8', 'http-equiv'=>'Content-Type'}
%meta{ 'content'=>'index, follow', 'name'=>'googlebot'}
%meta{ 'content'=>'follow, all', 'name'=>'Googlebot-Image'}
%meta{ 'content'=>'follow, all', 'name'=>'msnbot'}
%meta{ 'content'=>'follow, all', 'name'=>'Slurp'}
%meta{ 'content'=>'follow, all', 'name'=>'ZyBorg'}
%meta{ 'content'=>'follow, all', 'name'=>'Scooter'}
%meta{ 'content'=>'all', 'name'=>'spiders'}
%meta{ 'content'=>'all', 'name'=>'WEBCRAWLERS'}
%meta{ 'content'=>'noodp', 'name'=>'robots'}
%meta{ 'content'=>'noydir', 'name'=>'robots'}
%meta{ 'content'=>"#{web_setting.keywords}", 'name'=>'search engines'}

app/views/shareds/_nav.html.haml
.navbar-top
  %ul.left
    %li.only-responsive
      %a.button-nav-side{href: '#'}
        %i.fa.fa-bars
    %li.li-brand
      = link_to "#{image_tag 'logo6.png'}".html_safe, root_path
    %li.li-search-form
      = form_for :search, url: results_videos_path(params), method: 'get', html:{class: 'search-form'} do |f|
        .form-group.has-feedback
          %label.sr-only Search
          = text_field_tag :key, params[:key], class: 'form-control', placeholder: "Search"
          %span.glyphicon.glyphicon-search.form-control-feedback

  %ul.right
    - if current_user.present?
      %li
        = link_to 'LogOut', destroy_user_session_path, method: 'delete'
      %li.dropdown-toggle#dropdownMenu1{'data-toggle' => "dropdown", 'aria-haspopup' => "true", 'aria-expanded' => "false"}
        %a.thumb-avatar{href: '#'}
          #{image_tag current_user.avatar.url(:thumb), class: 'img-circle'} #{current_user.username} &nbsp; <i class="fa fa-caret-down" aria-hidden="true"></i>
      .dropdown
        %ul.dropdown-menu{'aria-labelledby' => "dropdownMenu1"}
          %li
            = link_to '<i class="fa fa-globe" aria-hidden="true"></i> Dashboard'.html_safe, userpage_dashboard_path
          %li
            = link_to '<i class="fa fa-heart" aria-hidden="true"></i> Whishlist'.html_safe, userpage_wishlists_path
          - if current_user.verified?
            %li
              = link_to '<i class="fa fa-film" aria-hidden="true"></i> My Videos'.html_safe, userpage_videos_path
          %li
            = link_to '<i class="fa fa-gear" aria-hidden="true"></i> Settings'.html_safe, edit_userpage_member_path(current_user)
          %li
            = link_to '<i class="fa fa-share fa-1" aria-hidden="true"></i> SignOut'.html_safe, destroy_user_session_path, method: 'delete'
    - else
      %li
        = link_to 'Register', new_user_registration_path
      %li
        = link_to 'Login', new_user_session_path
    %li.only-responsive
      = link_to 'Home', root_path

.rgba-black
  .sidebar-nav
    = render 'shareds/side_nav'
          

app/views/shareds/_popular.html.haml
%h4.titleize POPULAR
%ul.latest-list
  - @popular_videos.each_with_index do |v, index|
    %li
      = link_to video_path(v) do
        .cover
          - cache ["cover_video_popular_#{v.id}_#{v.updated_at.to_time.to_i}"] do
            = image_tag v.cover_image.url(:small)
        .category #{v.type_video.titleize if v.type_video.present?}
        - if v.series? && v.episodes.present?
          .title #{v.episodes.first.title}
        - else
          .title #{v.title}
        %small.view-eye
          %i.fa.fa-eye
          #{v.impressionist_count} Views

app/views/shareds/_sharethis.html.erb
<script type="text/javascript">var switchTo5x=true;</script>
<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script type="text/javascript">stLight.options({publisher: "85a5e2b6-1198-48e4-8cea-a5291ba2d1a6", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>
<span class='st_sharethis_large' displayText='ShareThis'></span>
<span class='st_facebook_large' displayText='Facebook'></span>
<span class='st_twitter_large' displayText='Tweet'></span>
<span class='st_linkedin_large' displayText='LinkedIn'></span>
<span class='st_pinterest_large' displayText='Pinterest'></span>
<span class='st_email_large' displayText='Email'></span>

app/views/shareds/_side_nav.html.haml
- if current_user.present?
  .col-md-12
    = link_to root_path do
      .thumb-avatar
        = image_tag current_user.avatar.url(:small)
  .col-md-12
    %center
      %p
        = link_to "<i class='fa fa-globe' aria-hidden='true'></i> #{current_user.try(:email)}".html_safe, userpage_dashboard_path
      = link_to "<i class='fa fa-gear' aria-hidden='true'></i> Setting Account".html_safe, edit_userpage_member_path(current_user), class: 'btn btn-success btn-xs'
.col-md-12
  %ul
    %li
      = link_to '<i class="fa fa-globe" aria-hidden="true"></i> Beranda'.html_safe, root_path, class: "#{'true' if params[:action] == 'home'}"
    - unless current_user.present?
      %li
        = link_to '<i class="fa fa-user" aria-hidden="true"></i> SignIn/SignUp'.html_safe, new_user_session_path
    - get_categories.each do |c|
      %li
        = link_to "<i class='fa fa-film' aria-hidden='true'></i> #{c.name.titleize} <small class='pull-right'>#{c.videos.actived.size}</small>".html_safe, videos_path(category: c), class: "#{c.slug == params[:category]}"

  .ads-google
    %br
    %strong RELEASE YEAR
    %br
    %br
    .row
      - (2008..Date.today.year).reverse_each do |y|
        .col-xs-4
          = link_to "#{y}", results_videos_path(year: y), class: "btn btn-info btn-xs btn-year #{y == params[:year].to_i}"

    %br
    %small.color-grey Share sovies-series.com to everyone ?
    %br
    %br
    .fb-share-button{"data-href" => "#{root_url}", "data-layout" => "button_count"}
    &nbsp;
    %a{:href => "https://twitter.com/intent/tweet?url=#{root_url}&text=Watch%20movies%20series%20videos.&via=movies-series", :target => "_blank", class: 'btn btn-info btn-xs'} <i class="fa fa-twitter" aria-hidden="true"></i> Share
    &nbsp;
    %a{:href => "https://plus.google.com/share?url=#{root_url}", :target => "_blank", class: 'btn btn-danger btn-xs'} <i class="fa fa-google-plus" aria-hidden="true"></i> Share
    %br
    %br