config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users,
    controllers: {
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations',
      sessions: 'sessions'
    },
    path_names: {
      sign_in:  'login',
      sign_out: 'logout',
      sign_up:  'register'
    }
    
  root 'public#home'
  get "sitemap.xml" => "sitemaps#index", format: "xml", as: 'sitemap'
  
  resources :videos do
    collection do
      get :episode
      get :results
    end
  end
  resources :wishlists

  namespace :userpage do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :members
    resources :videos
    resources :activities
    resources :wishlists
  end

  namespace :backend do
    get "dashboard", to: 'home#dashboard', as: 'dashboard_admin'
    resources :admins
    resources :members do
      collection do
        get :multiple_action
      end
    end
    resources :category_videos
    resources :videos do
      collection do
        get :multiple_action
      end
    end
    resources :web_settings
  end
end

app/controllers/backend/admins_controller.rb
class Backend::AdminsController < Backend::ApplicationController 
  before_action :class_name
  before_filter :draw_password, only: :update

  add_breadcrumb "Admins", :backend_admins_path

  def index
    @admins = collection.paginate(page: params[:page])
  end

  def show
    prepare_add_breadcrumb_action
    resource
  end

  def new
    prepare_add_breadcrumb_action
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(params_permit)
    @admin.type = "Admin"
    @admin.confirmation_token = nil
    @admin.confirmed_at = Time.now
    if @admin.save
      redirect_to :back, notice: "Successfully saved #{@resource_name}"
    else
      redirect_to :back
    end
  end

  def edit
    prepare_add_breadcrumb_action
    resource
  end

  def update
    resource

    if @admin.update(params_permit)
      redirect_to :back, notice: "Successfully saved #{@resource_name}"
    else
      redirect_to :back
    end
  end

  def destroy
    resource

    if @admin.destroy
      redirect_to :back
    else
      redirect_to :back
    end
  end

  private
    def resource
      @admin = Admin.find(params[:id])
    end

    def collection
      @admins = Admin.latest
    end

    def params_permit
      params.require(:admin).permit(
                                    :username, 
                                    :email, 
                                    :password, 
                                    :password_confirmation,
                                    :type,
                                    :avatar,
                                    :code,
                                    profile_attributes: [
                                      :first_name,
                                      :last_name,
                                      :born,
                                      :gender,
                                      :country,
                                      :province,
                                      :city,
                                      :phone,
                                      :address,
                                      :from,
                                      :user_id
                                    ])
    end

    def class_name
      @resource_name = 'Admin'
      @collection_name = 'Admins'
    end

    def draw_password
      %w(password password_confirmation).each do |attr|
        params[:admin].delete(attr)
      end if params[:admin] && params[:admin][:password].blank?
    end
end

app/controllers/backend/application_controller.rb
class Backend::ApplicationController < ApplicationController
  layout 'admin_lte_2'

  before_filter :authenticate_admin!

  add_breadcrumb "Dashboard", :backend_dashboard_admin_path

  def authenticate_admin!
    unless current_user.present? && (current_user.is_admin?)
      redirect_to root_path, alert: "Can't Access This Page!"
    end
  end

  protected
    def per_page
      params[:per_page] ||= 20
    end

    def page
      params[:page] ||= 1
    end

    def prepare_add_breadcrumb_action
      add_breadcrumb "#{params[:action]}"
    end
end

app/controllers/backend/category_videos_controller.rb
class Backend::CategoryVideosController < Backend::ApplicationController
  before_action :class_name
  add_breadcrumb "Category Videos", :backend_category_videos_path

  def index
    @category_videos = collection.paginate(page: page, per_page: per_page)
  end

  def new
    prepare_add_breadcrumb_action
    @category_video = CategoryVideo.new
  end

  def create
    @category_video = CategoryVideo.new(permitted_params)
    if @category_video.save
      redirect_to :back, notice: 'Your category video have been created!'
    else
      redirect_to :back, alert: 'Error'
    end
  end

  def edit
    prepare_add_breadcrumb_action
    resource
  end

  def update
    resource
    if @category_video.update(permitted_params)
      redirect_to :back, notice: 'Your category video have been updated!'
    else
      redirect_to :back, alert: 'Error'
    end
  end

  def destroy
    resource
    if @category_video.destroy
      redirect_to :back, notice: 'Your category video have been deleted!'
    else
      redirect_to :back, alert: 'Error'
    end
  end

  private
    def resource
      @category_video = CategoryVideo.find params[:id]
    end

    def collection
      @collection = CategoryVideo.latest
    end

    def permitted_params
      params.require(:category_video).permit(
                                    :id,
                                    :name, 
                                    :slug, 
                                    :cover_image, 
                                    :description
                                    )
    end

    def class_name
      @resource_name = 'Category Video'
      @collection_name = 'Category Videos'
    end
end

app/controllers/backend/home_controller.rb
class Backend::HomeController < Backend::ApplicationController 
  def dashboard
    add_breadcrumb "Home", backend_dashboard_admin_path
  end
end

app/controllers/backend/members_controller.rb
class Backend::MembersController < Backend::ApplicationController 
  before_action :class_name
  before_filter :draw_password, only: :update

  add_breadcrumb "Members", :backend_members_path

  def index
    add_breadcrumb "#{params[:action]}"
    @members = collection.paginate(page: page, per_page: per_page)
    @members_count = collection.size
  end

  def show
    prepare_add_breadcrumb_action
    resource
  end

  def new
    prepare_add_breadcrumb_action
    add_breadcrumb "#{params[:action]}"
    @member = Member.new
  end

  def create
    @member = Member.new(params_permit)

    if @member.save
      redirect_to :back, notice: "Successfully saved #{@resource_name}"
    else
      redirect_to :back
    end
  end

  def edit
    prepare_add_breadcrumb_action
    add_breadcrumb "#{params[:action]}"
    resource
  end

  def update
    resource

    if @member.update(params_permit)
      redirect_to :back, notice: "Successfully saved #{@resource_name}"
    else
      redirect_to :back
    end
  end

  def destroy
    resource

    if @member.destroy
      redirect_to :back
    else
      redirect_to :back
    end
  end

  def multiple_action
    if params[:ids].present?
      if params[:commit] == 'Do Verified'
        
        collect = params[:ids]

        Member.where(id: collect).each do |c|
          c.verified = true
          c.save
        end

        redirect_to :back, alert: 'Successfully set verified Members!'
      elsif params[:commit] == 'Do Featured'
        
        collect = params[:ids]

        Member.where(id: collect).each do |c|
          c.featured = true
          c.save
        end

        redirect_to :back, alert: 'Successfully set featured Members!'
      elsif params[:commit] == 'Do Destroy'
        collect = params[:ids]

        Member.where(id: collect).each do |c|
          c.destroy
        end

        redirect_to :back, alert: 'Successfully deleted Members!'
      else
        redirect_to :back, alert: 'Nothing checked!'
      end 
    end
  end

  private
    def resource
      @member = Member.find(params[:id])
    end

    def collection
      @member = Member.latest.search_by(params)
    end

    def params_permit
      params.require(:member).permit(
                                    :username, 
                                    :email, 
                                    :password, 
                                    :password_confirmation,
                                    :type,
                                    :avatar,
                                    :code,
                                    :verified,
                                    :featured,
                                    profile_attributes: [
                                      :first_name,
                                      :last_name,
                                      :born,
                                      :gender,
                                      :country,
                                      :province,
                                      :city,
                                      :phone,
                                      :address,
                                      :from,
                                      :user_id
                                    ])
    end

    def class_name
      @resource_name = 'Member'
      @collection_name = 'Members'
    end

    def draw_password
      %w(password password_confirmation).each do |attr|
        params[:member].delete(attr)
      end if params[:member] && params[:member][:password].blank?
    end
end

app/controllers/backend/videos_controller.rb
class Backend::VideosController < Backend::ApplicationController
  before_action :class_name
  add_breadcrumb "Videos", :backend_videos_path

  def index
    @videos = collection.paginate(page: page, per_page: per_page)
    @videos_count = collection.size
  end

  def new
    prepare_add_breadcrumb_action
    @video = Video.new
  end

  def create
    @video = Video.new(permitted_params)
    @video.user_id = current_user.id
    if @video.save
      redirect_to :back, notice: 'Your video have been created!'
    else
      redirect_to :back, alert: 'Error'
    end
  end

  def edit
    prepare_add_breadcrumb_action
    resource
  end

  def update
    resource
    if @video.update(permitted_params)
      redirect_to :back, notice: 'Your video have been updated!'
    else
      redirect_to :back, alert: 'Error'
    end
  end

  def destroy
    resource
    if @video.destroy
      redirect_to :back, notice: 'Your video have been deleted!'
    else
      redirect_to :back, alert: 'Error'
    end
  end

  def multiple_action
    if params[:ids].present?
      if params[:commit] == 'Do Verified'
        
        collect = params[:ids]

        Video.where(id: collect).each do |c|
          c.status = true
          c.save
        end

        redirect_to :back, alert: 'Successfully set verified videos!'
      elsif params[:commit] == 'Do Featured'
        
        collect = params[:ids]

        Video.where(id: collect).each do |c|
          c.featured = true
          c.save
        end

        redirect_to :back, alert: 'Successfully set featured videos!'
      elsif params[:commit] == 'Do Destroy'
        collect = params[:ids]

        Video.where(id: collect).each do |c|
          c.destroy
        end

        redirect_to :back, alert: 'Successfully deleted videos!'
      else
        redirect_to :back, alert: 'Nothing checked!'
      end 
    end
  end

  private
    def resource
      @video = Video.find params[:id]
    end

    def collection
      @collection = Video.latest.search_by(params)
    end

    def permitted_params
      params.require(:video).permit(
                                    :id,
                                    :title, 
                                    :director, 
                                    :actors, 
                                    :category,
                                    :description,
                                    :cover_image,
                                    :file,
                                    :session,
                                    :user_id,
                                    :code,
                                    :tag,
                                    :year,
                                    :status,
                                    :featured,
                                    :type_video,
                                    :kind,
                                    :category_video_id,
                                    :link_download_video,
                                    :click_link_download_video,
                                    :link_download_subtitle,
                                    :click_link_download_subtitle,
                                    episodes_attributes: [
                                      :id,
                                      :title,
                                      :episode,
                                      :link_video,
                                      :cover_image,
                                      :link_download_video,
                                      :click_link_download_video,
                                      :link_download_subtitle,
                                      :click_link_download_subtitle,
                                      :_destroy
                                    ])
    end

    def class_name
      @resource_name = 'Video'
      @collection_name = 'Videos'
    end
end

app/controllers/backend/web_settings_controller.rb
class Backend::WebSettingsController < Backend::ApplicationController 
  before_action :class_name
  add_breadcrumb "Web Settings", :backend_web_settings_path

  def index
    @web_settings = collection
  end

  def show
    prepare_add_breadcrumb_action
    resource
  end

  def new
    prepare_add_breadcrumb_action
    add_breadcrumb "#{params[:action]}"
    @web_setting = WebSetting.new
  end

  def create
    @web_setting = WebSetting.new(params_permit)

    if @web_setting.save
      redirect_to :back, notice: "Successfully saved #{@resource_name}"
    else
      redirect_to :back
    end
  end

  def edit
    prepare_add_breadcrumb_action
    add_breadcrumb "#{params[:action]}"
    resource
  end

  def update
    resource

    if @web_setting.update(params_permit)
      redirect_to :back, notice: "Successfully saved #{@resource_name}"
    else
      redirect_to :back
    end
  end

  def destroy
    resource

    if @web_setting.destroy
      redirect_to :back
    else
      redirect_to :back
    end
  end

  private
    def resource
      @web_setting = WebSetting.find(params[:id])
    end

    def collection
      @web_setting = WebSetting.latest
    end

    def params_permit
      params.require(:web_setting).permit(
                                          :title, 
                                          :description, 
                                          :keywords, 
                                          :header_tags, 
                                          :footer_tags, 
                                          :contact, 
                                          :email, 
                                          :favicon, 
                                          :logo, 
                                          :facebook, 
                                          :twitter, 
                                          :author, 
                                          :longitude, 
                                          :latitude, 
                                          :address
                                        )
    end

    def class_name
      @resource_name = 'WebSetting'
      @collection_name = 'WebSettings'
    end
end

app/views/backend/videos/_form.html.haml
- (['Movies','Series']).each do |c|
  .col-md-6
    .well
      %center
        %label #{c}
        .form-group
          = f.radio_button :kind, c, class: 'video_kind_movie'
.col-md-12
  .well
    .row
      .col-md-3.avatar-form
        = image_tag @video.cover_image.url(:small), style: 'width: 100%'
        %br
        %span.btn.btn-default.btn-choice{style: 'width: 100%'}
          Choice Cover
        = f.file_field :cover_image, style: "display: none"
      .col-md-9
        .row
          .col-md-12
            %label Title
            .form-group
              = f.text_field :title, class: 'form-control', placeholder: 'ex. The film, The movie ...'
            %label Link Video
            .form-group
              = f.text_field :file, class: 'form-control', placeholder: 'ex. https://www.youtube.com/watch?v=aK1PlNIvbkk ...'
          .col-md-6
            %label Link Download Video
            .form-group
              = f.text_field :link_download_video, class: 'form-control', placeholder: 'ex. https://openload.co/f/ldhuhSrB-1E ...'
          .col-md-6
            %label Link Download Subtitle
            .form-group
              = f.text_field :link_download_subtitle, class: 'form-control', placeholder: 'ex. https://openload.co/f/JuZGIjgVQHo ...'
          .col-md-6
            %label Category
            .form-group
              = f.select :category_video_id, options_for_select(get_categories.map{|c| [c.name, c.id]}, f.object.category_video_id), {prompt: 'Choice Category'}, class: 'form-control'
          .col-md-6
            %label Type
            .form-group
              = f.select :type_video, options_for_select(get_types, f.object.type_video), {prompt: 'Choice Type'}, class: 'form-control'
.col-md-6
  .well
    %center
      %label Status
      .form-group
        = f.check_box :status
.col-md-6
  .well
    %center
      %label Featured
      .form-group
        = f.check_box :featured
.col-md-6
  %label Year
  .form-group
    = f.select :year, options_for_select((1999..2016).map{|y| y}, f.object.year), {prompt: 'Choice Year'}, class: 'form-control'
.col-md-6
  %label Session
  .form-group
    = f.number_field :session, class: 'form-control', placeholder: 'ex. Session 1, Session2 ...'
.col-md-6
  %label Written By
  .form-group
    = f.text_field :director, class: 'form-control', placeholder: 'ex. Will Smith ...'
.col-md-6
  %label Actors
  .form-group
    = f.text_field :actors, class: 'form-control', placeholder: 'ex. Sandra Bulog, Cavin ...'
.col-md-12
  %label Synopsis
  .form-group
    = f.text_area :description, class: 'form-control', style: 'height: 200px'
.col-md-12
  %label Tag
  .form-group
    = f.text_field :tag, class: 'form-control', placeholder: 'movies, Action, Adventure, Comedy, Music, Sci-fi, USA, HD 720p, movies 2016'
.col-md-12
  = f.submit 'Save', class: "btn btn-success btn-login"

.col-md-12.section-video
  %h3 Episodes Video
  %hr
  = render partial: 'video_form', locals: {f: f}

  %br
  = f.submit 'Save', class: "btn btn-success btn-login"

app/views/backend/videos/_video_fields.html.haml
.col-md-12.nested-fields
  .well
    .row
      .col-md-4.video-form
        = image_tag f.object.cover_image.url(:small), style: 'width: 100%'
        %br
        = f.file_field :cover_image
      .col-md-8
        .row
          .col-md-12
            = link_to_remove_association "<i class='fa fa-times'></i>".html_safe, f, class: 'btn btn-danger btn-xs pull-right'
            %h6 Episode
            = f.number_field :episode, class: 'form-control'
            %h6 Title
            = f.text_field :title, class: 'form-control'
            %h6 Link Video
            = f.text_area :link_video, class: 'form-control', placeholder: 'Link Video'
          .col-md-6
            %h6 Link Download Video
            = f.text_field :link_download_video, class: 'form-control', placeholder: 'ex. https://openload.co/f/ldhuhSrB-1E ...'
          .col-md-6
            %h6 Link Download Subtitle
            = f.text_field :link_download_subtitle, class: 'form-control', placeholder: 'ex. https://openload.co/f/JuZGIjgVQHo ...'

app/views/backend/videos/_video_form.html.haml
.row
  .col-md-12
    %br
    = link_to_add_association f, :episodes, partial: 'video_fields', class: "btn btn-info btn-sm" do
      %i.fa.fa-film
      %span Add Episode
      
  = f.fields_for :episodes do |e|
    = render 'video_fields', f: e

app/views/backend/videos/edit.html.haml
.box
  .box-header
    %b
      = params[:action]
      = link_to 'Back To List', backend_videos_path, class: 'btn btn-info btn-xs pull-right'
    %hr
  .box-body.table-responsive
    = form_for @video, url: backend_video_path, method: 'put' do |f|
      = render 'form', f: f

app/views/backend/videos/index.html.haml
.box
  .box-header
    .row
      .col-md-6
        %label <b>#{@videos_count}</b> Result #{params[:controller].split('/')[1]}
        = form_for :search, url: backend_videos_path(params), method: 'get', html:{class: 'form-inline'} do |f|
          .form-group
            = text_field_tag :key, params[:key], class: 'form-control', placeholder: "Search", style: 'width: 300px'
          %button{type: "submit", class: "btn btn-default"} Search
      .col-md-6
        = link_to 'Create New', new_backend_video_path, class: 'btn btn-info pull-right'
  = form_for :multiple, url: multiple_action_backend_videos_path, method: 'get' do
    .col-md-12
      .btn-multiple-act
        = submit_tag 'Do Verified', value: 'Do Verified', class: 'btn btn-success'
        = submit_tag 'Do Featured', value: 'Do Featured', class: 'btn btn-warning'
        = submit_tag 'Do Destroy', value: 'Do Destroy', class: 'btn btn-danger'
    .box-body.table-responsive
      %table.table.table-hover
        %tr
          %th{width: '1%'}
            .check_all_box
              = check_box_tag :check_all 
          %th{width: '10%'} cover_image
          %th Title
          %th Status
          %th Type
          %th Category
          %th{width: '20%'} Tag
          %th Created At
          %th{width: '10%'}
            Action
        - @videos.each do |resource|
          %tr
            %td
              = check_box_tag 'ids[]', resource.id
            %td
              = image_tag resource.cover_image.url(:thumb)
            %td
              = resource.title
              %div
                = resource.featured?
              %div
              %i.fa.fa-eye 
              #{resource.impressionist_count(filter: :ip_address)} Views
            %td
              = resource.status?
            %td
              = resource.kind
            %td
              = resource.try(:category_video).try(:name)
            %td
              = resource.tag
            %td
              = resource.created_at.strftime("%I:%M %B, %d, %Y")
            %th
              = link_to '<i class="fa fa-wrench" aria-hidden="true"></i> Edit'.html_safe, edit_backend_video_path(resource), class: 'btn btn-primary btn-xs'
              = link_to '<i class="fa fa-trash" aria-hidden="true"></i> Delete'.html_safe, backend_video_path(resource), method: 'delete', data: {confirm: "Data #{@resource_name} successfully deleted!"}, class: 'btn btn-danger btn-xs'

    = will_paginate

app/views/backend/videos/new.html.haml
.box
  .box-header
    %b
      = params[:action]
      = link_to 'Back To List', backend_videos_path, class: 'btn btn-info btn-xs pull-right'
    %hr
  .box-body.table-responsive
    = form_for @video, url: backend_videos_path, method: 'post' do |f|
      = render 'form', f: f