config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users,
    controllers: {
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations',
      sessions: 'sessions'
    },
    path_names: {
      sign_in:  'login',
      sign_out: 'logout',
      sign_up:  'register'
    }
    
  root 'public#home'
  get "sitemap.xml" => "sitemaps#index", format: "xml", as: 'sitemap'
  
  resources :videos do
    collection do
      get :episode
      get :results
    end
  end
  resources :wishlists

  namespace :userpage do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :members
    resources :videos
    resources :activities
    resources :wishlists
  end

  namespace :backend do
    get "dashboard", to: 'home#dashboard', as: 'dashboard_admin'
    resources :admins
    resources :members do
      collection do
        get :multiple_action
      end
    end
    resources :category_videos
    resources :videos do
      collection do
        get :multiple_action
      end
    end
    resources :web_settings
  end
end

app/models/video.rb
class Video < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  before_create :prepare_code
  
  belongs_to :user
  has_many :wishlists, foreign_key: 'video_id', dependent: :destroy
  belongs_to :category_video

  scope :movies, ->{where(kind: 'Movies')}
  scope :series, ->{where(kind: 'Series')}
  scope :featured, ->{where(featured: true)}
  scope :actived, ->{where(status: true)}
  scope :popular, -> {order(view_count: :desc)}
  scope :latest, ->{order(created_at: :desc)}
  scope :oldest, ->{order(created_at: :asc)}
  scope :updatest, ->{order(updated_at: :desc)}
  scope :top_position, ->{order(featured: :desc)}
  scope :by_year, ->{order(year: :desc)}
  scope :bonds, ->{eager_load(:category_video)}

  mount_uploader :cover_image, ImageUploader

  is_impressionable
  has_many :impressions, as: :impressionable

  has_many :episodes, as: :episodeable, dependent: :destroy
  accepts_nested_attributes_for :episodes, reject_if: :all_blank, allow_destroy: true

  include TheVideo::VideoSearching
  ratyrate_rateable "service"

  def status?
    if self.status == true
      return "<label class='label label-success'>Active</label>".html_safe
    else
      return "<label class='label label-danger'>Pending</label>".html_safe
    end
  end

  def featured?
    if self.featured == true
      return "<b><i class='fa fa-flag'></i> Featured</b>".html_safe
    else
      return ""
    end
  end

  def check_your_wish(current_user)
    current_user.wishlists.where(user_id: current_user.id, video_id: self.id)
  end

  def movies?
    self.kind == 'Movies'
  end

  def series?
    self.kind == 'Series'
  end

  def data_new_today?
    today = Time.zone.now
    find_resource = Video.where(id: self.id).where("DATE(created_at) >= DATE(?) AND DATE(created_at) <= DATE(?)", today.at_beginning_of_week, today.at_end_of_week)
    
    if find_resource.present?
      return "<div class='label'>New</div>".html_safe
    else
      return ''
    end
  end

  private
    def prepare_code
      self.code = 'V'+ 6.times.map{Random.rand(10)}.join
    end
end

app/controllers/backend/videos_controller.rb
class Backend::VideosController < Backend::ApplicationController
  before_action :class_name
  add_breadcrumb "Videos", :backend_videos_path

  def index
    @videos = collection.paginate(page: page, per_page: per_page)
    @videos_count = collection.size
  end

  def new
    prepare_add_breadcrumb_action
    @video = Video.new
  end

  def create
    @video = Video.new(permitted_params)
    @video.user_id = current_user.id
    if @video.save
      redirect_to :back, notice: 'Your video have been created!'
    else
      redirect_to :back, alert: 'Error'
    end
  end

  def edit
    prepare_add_breadcrumb_action
    resource
  end

  def update
    resource
    if @video.update(permitted_params)
      redirect_to :back, notice: 'Your video have been updated!'
    else
      redirect_to :back, alert: 'Error'
    end
  end

  def destroy
    resource
    if @video.destroy
      redirect_to :back, notice: 'Your video have been deleted!'
    else
      redirect_to :back, alert: 'Error'
    end
  end

  def multiple_action
    if params[:ids].present?
      if params[:commit] == 'Do Verified'
        
        collect = params[:ids]

        Video.where(id: collect).each do |c|
          c.status = true
          c.save
        end

        redirect_to :back, alert: 'Successfully set verified videos!'
      elsif params[:commit] == 'Do Featured'
        
        collect = params[:ids]

        Video.where(id: collect).each do |c|
          c.featured = true
          c.save
        end

        redirect_to :back, alert: 'Successfully set featured videos!'
      elsif params[:commit] == 'Do Destroy'
        collect = params[:ids]

        Video.where(id: collect).each do |c|
          c.destroy
        end

        redirect_to :back, alert: 'Successfully deleted videos!'
      else
        redirect_to :back, alert: 'Nothing checked!'
      end 
    end
  end

  private
    def resource
      @video = Video.find params[:id]
    end

    def collection
      @collection = Video.latest.search_by(params)
    end

    def permitted_params
      params.require(:video).permit(
                                    :id,
                                    :title, 
                                    :director, 
                                    :actors, 
                                    :category,
                                    :description,
                                    :cover_image,
                                    :file,
                                    :session,
                                    :user_id,
                                    :code,
                                    :tag,
                                    :year,
                                    :status,
                                    :featured,
                                    :type_video,
                                    :kind,
                                    :category_video_id,
                                    :link_download_video,
                                    :click_link_download_video,
                                    :link_download_subtitle,
                                    :click_link_download_subtitle,
                                    episodes_attributes: [
                                      :id,
                                      :title,
                                      :episode,
                                      :link_video,
                                      :cover_image,
                                      :link_download_video,
                                      :click_link_download_video,
                                      :link_download_subtitle,
                                      :click_link_download_subtitle,
                                      :_destroy
                                    ])
    end

    def class_name
      @resource_name = 'Video'
      @collection_name = 'Videos'
    end
end

app/controllers/userpage/application_controller.rb
class Userpage::ApplicationController < ApplicationController
  before_filter :authenticate_user!
  before_action :prepare_for_videos

  layout 'userpage'

  def authenticate_user!
    unless current_user.present? && current_user.is_member?
      redirect_to root_path, alert: "Can't Access this page"
    else
      @count_videos = current_user.videos
    end
  end

  def prepare_for_videos
    @popular_videos = Video.actived.popular.limit(8)
  end
end

app/controllers/userpage/home_controller.rb
class Userpage::HomeController < Userpage::ApplicationController
  def dashboard
    @activities = current_user.activities.latest.paginate(page: page, per_page: per_page)
    if current_user.verified?
      @videos = current_user.videos.latest.limit(15)
    else
      @videos = current_user.wishlists.latest.limit(15)
    end
  end
end

app/controllers/userpage/members_controller.rb
class Userpage::MembersController < Userpage::ApplicationController
  before_filter :draw_password, only: :update

  def edit
    resource
  end

  def update
    resource
    if @member.update(permitted_params)
      redirect_to :back, notice: 'Your profile have been updated!'
    else
      redirect_to :back, alert: 'Error'
    end
  end

  private
    def draw_password
      %w(password password_confirmation).each do |attr|
        params[:member].delete(attr)
      end if params[:member] && params[:member][:password].blank?
    end

    def resource
      @member = User.find current_user
    end

    def permitted_params
      params.require(:member).permit(
                                    :username, 
                                    :email, 
                                    :password, 
                                    :password_confirmation,
                                    :type,
                                    :avatar,
                                    :code,
                                    profile_attributes: [
                                      :first_name,
                                      :last_name,
                                      :born,
                                      :gender,
                                      :country,
                                      :province,
                                      :city,
                                      :phone,
                                      :address,
                                      :from,
                                      :user_id
                                    ])
    end
end

app/controllers/userpage/videos_controller.rb
class Userpage::VideosController < Userpage::ApplicationController

  def index
    @videos = collection.paginate(page: page, per_page: per_page)
    @videos_count = collection.size
  end

  def new
    @video = Video.new
  end

  def create
    @video = Video.new(permitted_params)
    @video.user_id = current_user.id
    if @video.save
      redirect_to userpage_videos_path, notice: 'Your video have been created!'
    else
      redirect_to :back, alert: 'Error'
    end
  end

  def edit
    resource
  end

  def update
    resource
    if @video.update(permitted_params)
      redirect_to userpage_videos_path, notice: 'Your video have been updated!'
    else
      redirect_to :back, alert: 'Error'
    end
  end

  def destroy
    resource
    if @video.destroy
      redirect_to :back, notice: 'Your video have been deleted!'
    else
      redirect_to :back, alert: 'Error'
    end
  end

  private
    def resource
      @video = current_user.videos.find params[:id]
    end

    def collection
      @collection = current_user.videos.latest.search_by(params)
    end

    def permitted_params
      params.require(:video).permit(
                                    :id,
                                    :title, 
                                    :director, 
                                    :actors, 
                                    :category,
                                    :description,
                                    :cover_image,
                                    :file,
                                    :session,
                                    :user_id,
                                    :code,
                                    :tag,
                                    :year,
                                    :status,
                                    :featured,
                                    :type_video,
                                    :kind,
                                    :category_video_id,
                                    :link_download_video,
                                    :click_link_download_video,
                                    :link_download_subtitle,
                                    :click_link_download_subtitle,
                                    episodes_attributes: [
                                      :id,
                                      :title,
                                      :episode,
                                      :link_video,
                                      :cover_image,
                                      :link_download_video,
                                      :click_link_download_video,
                                      :link_download_subtitle,
                                      :click_link_download_subtitle,
                                      :_destroy
                                    ])
    end
end

app/controllers/userpage/wishlists_controller.rb
class Userpage::WishlistsController < Userpage::ApplicationController

  def index
    @wishlists = collection.paginate(page: page, per_page: 1)
    @videos_count = collection.size
  end

  def destroy
    resource
    if @wishlist.destroy
      redirect_to :back, notice: 'Your wishlist video have been deleted!'
    else
      redirect_to :back, alert: 'Error'
    end
  end

  private
    def resource
      @wishlist = current_user.wishlists.find params[:id]
    end

    def collection
      @collection = current_user.wishlists.latest.search_by(params)
    end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController  
  def index
    @category_video = CategoryVideo.find(params[:category])
    @collection = @category_video.videos.actived.top_position.by_year.latest.search_by(params)
    @videos = @collection.paginate(page: page, per_page: per_page)
    
    @popular_videos = @category_video.videos.actived.popular.limit(8)
    @featured_videos = @category_video.videos.actived.featured.updatest.limit(6)
    impressionist(@category_video, 'message')
  end

  def show
    @video = Video.find_by(slug: params[:id])

    if @video.present?
      prepare_quick_count(@video)
      @popular_videos = Video.actived.popular.limit(8)
      @other_videos = collection.where(category_video_id: @video.category_video_id).limit(10)
      impressionist(@video, 'message')

      if current_user.present?
        prepare_activity("Has been viewed video <a href='#{video_url(@video)}'>#{@video.title}</a>", 'Video', @video.id, video_url(@video), current_user)
      end
    else
      redirect_to root_path, alert: "Can't Access this page"
    end
  end

  def episode
    @video = Video.find_by(slug: params[:video])
  
    if @video.present?
      @episode = @video.episodes.find_by(episode: params[:episode])

      if @episode.present?
        @popular_videos = Video.actived.popular.limit(8)
        impressionist(@episode, 'message')

        if current_user.present?
          prepare_activity("Has been viewed series video <a href='#{episode_videos_path(episode: @episode.episode, video: @video.slug)}'>#{@episode.title}</a>", 'Episode', @episode.id, episode_videos_path(episode: @episode.episode, video: @video.slug), current_user)
        end
      else
        redirect_to root_path, alert: "Can't Access this page"
      end
    else
      redirect_to root_path, alert: "Can't Access this page"
    end
  end

  def results
    @collection = collection
    @videos = @collection.paginate(page: page, per_page: per_page)
    @popular_videos = Video.actived.popular.limit(8)
  end

  private
    def resource
      @video = Video.find params[:id]
    end

    def collection
      @collection = Video.actived.by_year.latest.search_by(params)
    end

    def prepare_quick_count(resource)
      resource = Video.find(resource)
      resource.view_count = resource.view_count+1
      resource.save
    end
end

app/views/userpage/videos/_form.html.haml
- (['Movies','Series']).each do |c|
  .col-md-6
    .border-well
      %center
        %b #{c}
        %div
          = f.radio_button :kind, c, class: 'video_kind_movie'
.col-md-12
  .border-well
    .row
      .col-md-3.avatar-form
        = image_tag @video.cover_image.url(:small), style: 'width: 100%'
        %br
        %span.btn.btn-default.btn-xs.btn-choice{style: 'width: 100%'}
          Choice cover_image
        = f.file_field :cover_image, style: "display: none"
      .col-md-9
        .row
          .col-md-12
            %label Title
            .form-group
              = f.text_field :title, class: 'form-control', placeholder: 'ex. The film, The movie ...'
            %label Link Video
            .form-group
              = f.text_field :file, class: 'form-control', placeholder: 'ex. https://www.youtube.com/watch?v=aK1PlNIvbkk ...'
          .col-md-6
            %label Link Download Video
            .form-group
              = f.text_field :link_download_video, class: 'form-control', placeholder: 'ex. https://openload.co/f/ldhuhSrB-1E ...'
          .col-md-6
            %label Link Download Subtitle
            .form-group
              = f.text_field :link_download_subtitle, class: 'form-control', placeholder: 'ex. https://openload.co/f/JuZGIjgVQHo ...'
.col-md-6
  %label Category
  .form-group
    = f.select :category_video_id, options_for_select(get_categories.map{|c| [c.name, c.id]}, f.object.category_video_id), {prompt: 'Choice Category'}, class: 'form-control'
.col-md-6
  %label Type
  .form-group
    = f.select :type_video, options_for_select(get_types, f.object.type_video), {prompt: 'Choice Type'}, class: 'form-control'
.col-md-6
  %label Year
  .form-group
    = f.select :year, options_for_select((1999..2016).map{|y| y}, f.object.year), {prompt: 'Choice Year'}, class: 'form-control'
.col-md-6
  %label Session
  .form-group
    = f.number_field :session, class: 'form-control', placeholder: 'ex. Session 1, Session2 ...'
.col-md-6
  %label Written By
  .form-group
    = f.text_field :director, class: 'form-control', placeholder: 'ex. Will Smith ...'
.col-md-6
  %label Actors
  .form-group
    = f.text_field :actors, class: 'form-control', placeholder: 'ex. Sandra Bulog, Cavin ...'
.col-md-12
  %label Synopsis
  .form-group
    = f.text_area :description, class: 'form-control', style: 'height: 200px'
.col-md-12
  %label Tag
  .form-group
    = f.text_field :tag, class: 'form-control', placeholder: 'movies, Action, Adventure, Comedy, Music, Sci-fi, USA, HD 720p, movies 2016'
.col-md-12
  = f.submit 'Save', class: "btn btn-success btn-login"

.col-md-12.section-video
  %br
  %h3 Episodes Video
  %hr
  = render partial: 'video_form', locals: {f: f}

  %br
  = f.submit 'Save', class: "btn btn-success btn-login"

app/views/userpage/videos/_video_fields.html.haml
.col-md-12.nested-fields
  .well
    .row
      .col-md-4.video-form
        = image_tag f.object.cover_image.url(:small), style: 'width: 100%'
        %br
        = f.file_field :cover_image
      .col-md-8
        .row
          .col-md-12
            = link_to_remove_association "<i class='fa fa-times'></i>".html_safe, f, class: 'btn btn-danger btn-xs pull-right'
            %h6 Episode
            = f.number_field :episode, class: 'form-control'
            %h6 Title
            = f.text_field :title, class: 'form-control'
            %h6 Link Video
            = f.text_area :link_video, class: 'form-control', placeholder: 'Link Video'
          .col-md-6
            %h6 Link Download Video
            = f.text_field :link_download_video, class: 'form-control', placeholder: 'ex. https://openload.co/f/ldhuhSrB-1E ...'
          .col-md-6
            %h6 Link Download Subtitle
            = f.text_field :link_download_subtitle, class: 'form-control', placeholder: 'ex. https://openload.co/f/JuZGIjgVQHo ...'

app/views/userpage/videos/_video_form.html.haml
.row
  .col-md-12
    = link_to_add_association f, :episodes, partial: 'video_fields', class: "btn btn-info btn-sm", style: 'margin-bottom:10px;' do
      %i.fa.fa-film &nbsp;
      %span Add Episode

  = f.fields_for :episodes do |e|
    = render 'video_fields', f: e

app/views/userpage/videos/edit.html.haml
.col-md-12
  .content
    = link_to '< Back', userpage_videos_path, class: 'btn btn-info btn-xs pull-left'
    %br
    %hr
    .box-form
      %h3{align: 'center'} Edit Video
      = form_for @video, url: userpage_video_path(@video), method: 'put' do |f|
        = render 'form', f: f

app/views/userpage/videos/index.html.haml
.col-xs-8
  = form_for :search, url: userpage_videos_path(params), method: 'get', html:{class: 'form-inline'} do |f|
    .form-group
      .label-results Found <b>#{@videos_count}</b> Result Videos
      = text_field_tag :key, params[:key], class: 'form-control search-input-keywords', placeholder: "Search"
.col-xs-4
  %br
  = link_to 'Create New', new_userpage_video_path, class: 'btn btn-info pull-right'
.col-md-12
  %hr
  - if @videos.present?
    - @videos.each_with_index do |v, index|
      .content-title
        .row
          .col-md-3
            .cover
              = image_tag v.cover_image.url(:small)
          .col-md-9
            %table.table
              %tr
                %td{width: '25%'}
                  %b TITLE
                %td : #{link_to "#{v.title} (#{v.code})", video_path(v)}
              %tr
                %td 
                  %b STATUS
                %td : #{v.status?} &nbsp; #{v.featured?}
              %tr
                %td 
                  %b TYPE
                %td : #{v.kind}
              %tr
                %td 
                  %b RILIS
                %td : #{v.year}
              %tr
                %td 
                  %b WRITTEN BY
                %td : #{v.director}
              %tr
                %td 
                  %b ACTORS
                %td : #{v.actors}
              %tr
                %td 
                  %b CATEGORY
                %td : #{v.tag}
              %tr
                %td 
                  %b CREATED AT
                %td : #{v.created_at.strftime("%I:%M %B, %d, %Y")}
            
          .col-md-12
            %hr
          .col-md-6
            = link_to '<i class="fa fa-wrench" aria-hidden="true"></i> Edit'.html_safe, edit_userpage_video_path(v), class: 'btn btn-info btn-xs'
            = link_to '<i class="fa fa-trash" aria-hidden="true"></i> Delete'.html_safe, userpage_video_path(v), method: 'delete', data: {confirm: "Data #{v.title} successfully deleted!"}, class: 'btn btn-danger btn-xs'
          .col-md-6
            %span.pull-right
              %i.fa.fa-eye
              #{v.impressionist_count} Views
  - else
    .alert.alert-warning{align: 'center'} No data results!

.col-md-12
  = will_paginate

app/views/userpage/videos/new.html.haml
.col-md-12
  .content
    = link_to '< Back', userpage_videos_path, class: 'btn btn-info btn-xs pull-left'
    %br
    %hr
    .box-form
      %h3{align: 'center'} Create New Video
      = form_for @video, url: userpage_videos_path, method: 'post' do |f|
        = render 'form', f: f