config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users,
    controllers: {
      omniauth_callbacks: 'omniauth_callbacks',
      registrations: 'registrations',
      sessions: 'sessions'
    },
    path_names: {
      sign_in:  'login',
      sign_out: 'logout',
      sign_up:  'register'
    }
    
  root 'public#home'
  get "sitemap.xml" => "sitemaps#index", format: "xml", as: 'sitemap'
  
  resources :videos do
    collection do
      get :episode
      get :results
    end
  end
  resources :wishlists

  namespace :userpage do
    get 'dashboard', to: 'home#dashboard', as: 'dashboard'
    resources :members
    resources :videos
    resources :activities
    resources :wishlists
  end

  namespace :backend do
    get "dashboard", to: 'home#dashboard', as: 'dashboard_admin'
    resources :admins
    resources :members do
      collection do
        get :multiple_action
      end
    end
    resources :category_videos
    resources :videos do
      collection do
        get :multiple_action
      end
    end
    resources :web_settings
  end
end

app/controllers/backend/admins_controller.rb
class Backend::AdminsController < Backend::ApplicationController 
  before_action :class_name
  before_filter :draw_password, only: :update

  add_breadcrumb "Admins", :backend_admins_path

  def index
    @admins = collection.paginate(page: params[:page])
  end

  def show
    prepare_add_breadcrumb_action
    resource
  end

  def new
    prepare_add_breadcrumb_action
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(params_permit)
    @admin.type = "Admin"
    @admin.confirmation_token = nil
    @admin.confirmed_at = Time.now
    if @admin.save
      redirect_to :back, notice: "Successfully saved #{@resource_name}"
    else
      redirect_to :back
    end
  end

  def edit
    prepare_add_breadcrumb_action
    resource
  end

  def update
    resource

    if @admin.update(params_permit)
      redirect_to :back, notice: "Successfully saved #{@resource_name}"
    else
      redirect_to :back
    end
  end

  def destroy
    resource

    if @admin.destroy
      redirect_to :back
    else
      redirect_to :back
    end
  end

  private
    def resource
      @admin = Admin.find(params[:id])
    end

    def collection
      @admins = Admin.latest
    end

    def params_permit
      params.require(:admin).permit(
                                    :username, 
                                    :email, 
                                    :password, 
                                    :password_confirmation,
                                    :type,
                                    :avatar,
                                    :code,
                                    profile_attributes: [
                                      :first_name,
                                      :last_name,
                                      :born,
                                      :gender,
                                      :country,
                                      :province,
                                      :city,
                                      :phone,
                                      :address,
                                      :from,
                                      :user_id
                                    ])
    end

    def class_name
      @resource_name = 'Admin'
      @collection_name = 'Admins'
    end

    def draw_password
      %w(password password_confirmation).each do |attr|
        params[:admin].delete(attr)
      end if params[:admin] && params[:admin][:password].blank?
    end
end

app/controllers/backend/application_controller.rb
class Backend::ApplicationController < ApplicationController
  layout 'admin_lte_2'

  before_filter :authenticate_admin!

  add_breadcrumb "Dashboard", :backend_dashboard_admin_path

  def authenticate_admin!
    unless current_user.present? && (current_user.is_admin?)
      redirect_to root_path, alert: "Can't Access This Page!"
    end
  end

  protected
    def per_page
      params[:per_page] ||= 20
    end

    def page
      params[:page] ||= 1
    end

    def prepare_add_breadcrumb_action
      add_breadcrumb "#{params[:action]}"
    end
end

app/controllers/backend/category_videos_controller.rb
class Backend::CategoryVideosController < Backend::ApplicationController
  before_action :class_name
  add_breadcrumb "Category Videos", :backend_category_videos_path

  def index
    @category_videos = collection.paginate(page: page, per_page: per_page)
  end

  def new
    prepare_add_breadcrumb_action
    @category_video = CategoryVideo.new
  end

  def create
    @category_video = CategoryVideo.new(permitted_params)
    if @category_video.save
      redirect_to :back, notice: 'Your category video have been created!'
    else
      redirect_to :back, alert: 'Error'
    end
  end

  def edit
    prepare_add_breadcrumb_action
    resource
  end

  def update
    resource
    if @category_video.update(permitted_params)
      redirect_to :back, notice: 'Your category video have been updated!'
    else
      redirect_to :back, alert: 'Error'
    end
  end

  def destroy
    resource
    if @category_video.destroy
      redirect_to :back, notice: 'Your category video have been deleted!'
    else
      redirect_to :back, alert: 'Error'
    end
  end

  private
    def resource
      @category_video = CategoryVideo.find params[:id]
    end

    def collection
      @collection = CategoryVideo.latest
    end

    def permitted_params
      params.require(:category_video).permit(
                                    :id,
                                    :name, 
                                    :slug, 
                                    :cover_image, 
                                    :description
                                    )
    end

    def class_name
      @resource_name = 'Category Video'
      @collection_name = 'Category Videos'
    end
end

app/controllers/backend/home_controller.rb
class Backend::HomeController < Backend::ApplicationController 
  def dashboard
    add_breadcrumb "Home", backend_dashboard_admin_path
  end
end

app/controllers/backend/members_controller.rb
class Backend::MembersController < Backend::ApplicationController 
  before_action :class_name
  before_filter :draw_password, only: :update

  add_breadcrumb "Members", :backend_members_path

  def index
    add_breadcrumb "#{params[:action]}"
    @members = collection.paginate(page: page, per_page: per_page)
    @members_count = collection.size
  end

  def show
    prepare_add_breadcrumb_action
    resource
  end

  def new
    prepare_add_breadcrumb_action
    add_breadcrumb "#{params[:action]}"
    @member = Member.new
  end

  def create
    @member = Member.new(params_permit)

    if @member.save
      redirect_to :back, notice: "Successfully saved #{@resource_name}"
    else
      redirect_to :back
    end
  end

  def edit
    prepare_add_breadcrumb_action
    add_breadcrumb "#{params[:action]}"
    resource
  end

  def update
    resource

    if @member.update(params_permit)
      redirect_to :back, notice: "Successfully saved #{@resource_name}"
    else
      redirect_to :back
    end
  end

  def destroy
    resource

    if @member.destroy
      redirect_to :back
    else
      redirect_to :back
    end
  end

  def multiple_action
    if params[:ids].present?
      if params[:commit] == 'Do Verified'
        
        collect = params[:ids]

        Member.where(id: collect).each do |c|
          c.verified = true
          c.save
        end

        redirect_to :back, alert: 'Successfully set verified Members!'
      elsif params[:commit] == 'Do Featured'
        
        collect = params[:ids]

        Member.where(id: collect).each do |c|
          c.featured = true
          c.save
        end

        redirect_to :back, alert: 'Successfully set featured Members!'
      elsif params[:commit] == 'Do Destroy'
        collect = params[:ids]

        Member.where(id: collect).each do |c|
          c.destroy
        end

        redirect_to :back, alert: 'Successfully deleted Members!'
      else
        redirect_to :back, alert: 'Nothing checked!'
      end 
    end
  end

  private
    def resource
      @member = Member.find(params[:id])
    end

    def collection
      @member = Member.latest.search_by(params)
    end

    def params_permit
      params.require(:member).permit(
                                    :username, 
                                    :email, 
                                    :password, 
                                    :password_confirmation,
                                    :type,
                                    :avatar,
                                    :code,
                                    :verified,
                                    :featured,
                                    profile_attributes: [
                                      :first_name,
                                      :last_name,
                                      :born,
                                      :gender,
                                      :country,
                                      :province,
                                      :city,
                                      :phone,
                                      :address,
                                      :from,
                                      :user_id
                                    ])
    end

    def class_name
      @resource_name = 'Member'
      @collection_name = 'Members'
    end

    def draw_password
      %w(password password_confirmation).each do |attr|
        params[:member].delete(attr)
      end if params[:member] && params[:member][:password].blank?
    end
end

app/controllers/backend/videos_controller.rb
class Backend::VideosController < Backend::ApplicationController
  before_action :class_name
  add_breadcrumb "Videos", :backend_videos_path

  def index
    @videos = collection.paginate(page: page, per_page: per_page)
    @videos_count = collection.size
  end

  def new
    prepare_add_breadcrumb_action
    @video = Video.new
  end

  def create
    @video = Video.new(permitted_params)
    @video.user_id = current_user.id
    if @video.save
      redirect_to :back, notice: 'Your video have been created!'
    else
      redirect_to :back, alert: 'Error'
    end
  end

  def edit
    prepare_add_breadcrumb_action
    resource
  end

  def update
    resource
    if @video.update(permitted_params)
      redirect_to :back, notice: 'Your video have been updated!'
    else
      redirect_to :back, alert: 'Error'
    end
  end

  def destroy
    resource
    if @video.destroy
      redirect_to :back, notice: 'Your video have been deleted!'
    else
      redirect_to :back, alert: 'Error'
    end
  end

  def multiple_action
    if params[:ids].present?
      if params[:commit] == 'Do Verified'
        
        collect = params[:ids]

        Video.where(id: collect).each do |c|
          c.status = true
          c.save
        end

        redirect_to :back, alert: 'Successfully set verified videos!'
      elsif params[:commit] == 'Do Featured'
        
        collect = params[:ids]

        Video.where(id: collect).each do |c|
          c.featured = true
          c.save
        end

        redirect_to :back, alert: 'Successfully set featured videos!'
      elsif params[:commit] == 'Do Destroy'
        collect = params[:ids]

        Video.where(id: collect).each do |c|
          c.destroy
        end

        redirect_to :back, alert: 'Successfully deleted videos!'
      else
        redirect_to :back, alert: 'Nothing checked!'
      end 
    end
  end

  private
    def resource
      @video = Video.find params[:id]
    end

    def collection
      @collection = Video.latest.search_by(params)
    end

    def permitted_params
      params.require(:video).permit(
                                    :id,
                                    :title, 
                                    :director, 
                                    :actors, 
                                    :category,
                                    :description,
                                    :cover_image,
                                    :file,
                                    :session,
                                    :user_id,
                                    :code,
                                    :tag,
                                    :year,
                                    :status,
                                    :featured,
                                    :type_video,
                                    :kind,
                                    :category_video_id,
                                    :link_download_video,
                                    :click_link_download_video,
                                    :link_download_subtitle,
                                    :click_link_download_subtitle,
                                    episodes_attributes: [
                                      :id,
                                      :title,
                                      :episode,
                                      :link_video,
                                      :cover_image,
                                      :link_download_video,
                                      :click_link_download_video,
                                      :link_download_subtitle,
                                      :click_link_download_subtitle,
                                      :_destroy
                                    ])
    end

    def class_name
      @resource_name = 'Video'
      @collection_name = 'Videos'
    end
end

app/controllers/backend/web_settings_controller.rb
class Backend::WebSettingsController < Backend::ApplicationController 
  before_action :class_name
  add_breadcrumb "Web Settings", :backend_web_settings_path

  def index
    @web_settings = collection
  end

  def show
    prepare_add_breadcrumb_action
    resource
  end

  def new
    prepare_add_breadcrumb_action
    add_breadcrumb "#{params[:action]}"
    @web_setting = WebSetting.new
  end

  def create
    @web_setting = WebSetting.new(params_permit)

    if @web_setting.save
      redirect_to :back, notice: "Successfully saved #{@resource_name}"
    else
      redirect_to :back
    end
  end

  def edit
    prepare_add_breadcrumb_action
    add_breadcrumb "#{params[:action]}"
    resource
  end

  def update
    resource

    if @web_setting.update(params_permit)
      redirect_to :back, notice: "Successfully saved #{@resource_name}"
    else
      redirect_to :back
    end
  end

  def destroy
    resource

    if @web_setting.destroy
      redirect_to :back
    else
      redirect_to :back
    end
  end

  private
    def resource
      @web_setting = WebSetting.find(params[:id])
    end

    def collection
      @web_setting = WebSetting.latest
    end

    def params_permit
      params.require(:web_setting).permit(
                                          :title, 
                                          :description, 
                                          :keywords, 
                                          :header_tags, 
                                          :footer_tags, 
                                          :contact, 
                                          :email, 
                                          :favicon, 
                                          :logo, 
                                          :facebook, 
                                          :twitter, 
                                          :author, 
                                          :longitude, 
                                          :latitude, 
                                          :address
                                        )
    end

    def class_name
      @resource_name = 'WebSetting'
      @collection_name = 'WebSettings'
    end
end

app/views/backend/admins/_form.html.haml
.row
  .col-md-12
    %center.avatar-form
      = image_tag @admin.avatar.url(:thumb), class: 'img-circle'
      %br
      %span.btn.btn-info.btn-choice
        Choice Avatar
      = u.file_field :avatar, style: "display: none"
    %br
    %br
  .col-md-6
    .form-group
      = u.label :username
      = u.text_field :username, class: "form-control", placeholder: "Username", required: true

  .col-md-6
    .form-group
      = u.label :email
      = u.email_field :email, class: "form-control", placeholder: "Email", required: true

  .col-md-6
    .form-group
      = u.label :password
      = u.password_field :password, class: "form-control", placeholder: "Password"

  .col-md-6
    .form-group
      = u.label :password_confirmation
      = u.password_field :password_confirmation, class: "form-control", placeholder: "Password Confirmation"

  .col-md-12
    %hr
    
  .col-md-6
    .form-group
      = f.label :first_name
      = f.text_field :first_name, class: "form-control", placeholder: "First Name", required: true

  .col-md-6
    .form-group
      = f.label :last_name
      = f.text_field :last_name, class: "form-control", placeholder: "Last Name", required: true

  .col-md-6
    .form-group
      = f.label :birthday
      %div
        = f.date_select :born, {start_year: (Date.today.year-60), end_year:   (Date.today.year-12), order: [:day, :month, :year], prompt: { day:   'Day', month: 'Month', year:  'Year'}}, {class: 'form-control select-birthday'}

  .col-md-6
    .form-group
      = f.label :gender
      = f.select :gender, ["Female", "Male"], {prompt: 'Choice Gender'}, class: 'form-control', required: true

  .col-md-6
    .form-group
      = f.label :phone
      = f.text_field :phone, class: "form-control", placeholder: "Phone", required: true

  .col-md-6
    .form-group
      = f.label :country
      = f.country_select("country", { priority_countries: ["ID"], selected: f.object.country }, { class: 'form-control', data: { attribute: "value" } })

  .col-md-6
    .form-group
      = f.label :province
      = f.text_field :province, class: "form-control", placeholder: "Province", required: true

  .col-md-6
    .form-group
      = f.label :city
      = f.text_field :city, class: "form-control", placeholder: "City", required: true

  .col-md-12
    .form-group
      = f.label :address
      = f.text_field :address, class: "form-control", placeholder: "Address", required: true

  .col-md-12
    = f.submit 'Update', class: "btn btn-success btn-login"

app/views/backend/admins/edit.html.haml
.box
  .box-header
    %b
      = params[:action]
      = link_to 'Back To List', backend_admins_path, class: 'btn btn-info btn-xs pull-right'
    %hr
  .box-body.table-responsive
    = form_for @admin, url: backend_admin_path, method: 'put' do |u|
      = u.fields_for :profile do |f|
        = render 'form', {f: f, u: u}

app/views/backend/admins/index.html.haml
.box
  .box-header
    %b
      Data #{params[:controller].split('/')[1]}
      = link_to 'Create New', new_backend_admin_path, class: 'btn btn-info btn-xs pull-right'
  .box-body.table-responsive
    %table.table.table-hover
      %tr
        %th{width: '10%'}
          Username
        %th Email
        %th Address
        %th Created At
        %th{width: '15%'}
          Action
      - @admins.each do |resource|
        %tr
          %td
            = resource.username
          %td
            = resource.email
          %td
            = resource.profile.place_info
          %td
            = resource.created_at.strftime("%I:%M %B, %d, %Y")
          %th
            = link_to '<i class="fa fa-wrench" aria-hidden="true"></i> Edit'.html_safe, edit_backend_admin_path(resource), class: 'btn btn-primary btn-xs'
            = link_to '<i class="fa fa-trash" aria-hidden="true"></i> Delete'.html_safe, backend_admin_path(resource), method: 'delete', data: {confirm: "Data #{@resource_name} successfully deleted!"}, class: 'btn btn-danger btn-xs'

    = will_paginate

app/views/backend/admins/new.html.haml
.box
  .box-header
    %b
      = params[:action]
      = link_to 'Back To List', backend_admins_path, class: 'btn btn-info btn-xs pull-right'
    %hr
  .box-body.table-responsive
    = form_for @admin, url: backend_admins_path, method: 'post' do |u|
      = u.fields_for :profile do |f|
        = render 'form', {f: f, u: u}